#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor LVDS-1 -d I II III IV
bspc monitor HDMI-2 -d V VI VII
bspc monitor VGA-1 -d VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# enable transparency
xcompmgr

# start polybar
$HOME/.config/polybar/launch.sh
